version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.0-node-browsers-legacy
        environment:
          RAILS_ENV: test
          DB_HOST: 127.0.0.1
      - image: circleci/mysql:8.0-ram
        environment:
          DB_USERNAME: "root"
          DB_PASSWORD: ""
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-
      - run: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - run: yarn install
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run:
          name: Rubocop
          command: bundle exec rubocop -a
      - run:
          name: Lint
          command: |
            bundle exec slim-lint app/views -c config/slim_lint.yml
      - run:
          name: Test
          command: |
            bundle exec rake db:schema:load
            ./bin/test

workflows:
  version: 2
  rubocop_rspec:
    jobs:
      - build
