version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.5-node-browsers-legacy
        environment:
          RAILS_ENV: test
          DATABASE_URL: "postgres://myapp@localhost/myapp-test"
      - image: circleci/postgres:11.3
        environment:
          POSTGRES_USER: myapp
          POSTGRES_DB: myapp-test
          POSTGRES_PASSWORD: ""
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-
      - run: gem install bundler
      - run: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - run: yarn install
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run:
          name: Rubocop
          command: bundle exec rubocop -a
      - run:
          name: Lint
          command: |
            bundle exec slim-lint app/views -c config/slim_lint.yml
      - run:
          name: Test
          command: |
            bundle exec rake db:create
            bundle exec rake db:schema:load
            ./bin/test

workflows:
  version: 2
  rubocop_rspec:
    jobs:
      - build
